firstname = input("Enter first name:")
print("My first name is", firstname)
lastname = input("Enter last name:")
print("My last name is", lastname)
age = int(input("Enter your age:"))
print("I am", age, "years old")